# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d2aa6c2423819c77d157a9b36921194fd03935711f735974d32c49dbd7d62f02033a428e8cbc9e7ce27bbb7ffa9678e76e778bd432fb890149e243a3d216bb

test:
  secret_key_base: a18e6fdec2dfb2ce7b47695bc5606bc921ce7e79f0c0ce02e9c28c4c679ccdcb865784674b7afbe98f151f9a5e8fb35b06b6488c4e7283326ecbc9192c8bfd81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
